//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RA2_YR_Config.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RA2_YR_Config.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ddraw]
        ///RealDDrawPath=AUTO
        ///BltMirror=0
        ///BltNoTearing=0
        ///ColorFix=0
        ///DisableHighDpiScaling=0
        ///FakeVsync=0
        ///FakeVsyncInterval=0
        ///ForceBltNoTearing=0
        ///ForceDirectDrawEmulation=0
        ///NoVideoMemory=0
        ///SingleProcAffinity=0
        ///ShowFPS=0
        ///.
        /// </summary>
        internal static string aqrit {
            get {
                return ResourceManager.GetString("aqrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Hotkey]
        ///CenterView=12
        ///Options=27
        ///CenterOnRadarEvent=32
        ///RightSidebarUp=33
        ///RightSidebarDown=34
        ///LeftSidebarDown=35
        ///LeftSidebarUp=36
        ///Delete=46
        ///TeamSelect_10=48
        ///TeamSelect_1=49
        ///TeamSelect_2=50
        ///TeamSelect_3=51
        ///TeamSelect_4=52
        ///TeamSelect_5=53
        ///TeamSelect_6=54
        ///TeamSelect_7=55
        ///TeamSelect_8=56
        ///TeamSelect_9=57
        ///ToggleAlliance=65
        ///PlaceBeacon=66
        ///AllToCheer=67
        ///DeployObject=68
        ///InfantryTab=69
        ///Follow=70
        ///GuardObject=71
        ///CenterBase=72
        ///ToggleRepair=75
        ///ToggleSell=76
        ///NextObject=78
        ///CombatantSelect=80
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keyboardini {
            get {
                return ResourceManager.GetString("keyboardini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Hotkey]
        ///CenterView=12
        ///Options=27
        ///CenterOnRadarEvent=32
        ///RightSidebarUp=33
        ///RightSidebarDown=34
        ///LeftSidebarDown=35
        ///LeftSidebarUp=36
        ///TeamSelect_10=48
        ///TeamSelect_1=49
        ///TeamSelect_2=50
        ///TeamSelect_3=51
        ///TeamSelect_4=52
        ///TeamSelect_5=53
        ///TeamSelect_6=54
        ///TeamSelect_7=55
        ///TeamSelect_8=56
        ///TeamSelect_9=57
        ///ToggleAlliance=65
        ///PlaceBeacon=66
        ///AllToCheer=67
        ///DeployObject=68
        ///InfantryTab=69
        ///Follow=70
        ///GuardObject=71
        ///CenterBase=72
        ///ToggleRepair=75
        ///ToggleSell=76
        ///PreviousObject=77
        ///NextObject=78
        ///CombatantSel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keyboardmdini {
            get {
                return ResourceManager.GetString("keyboardmdini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MultiPlayer]
        ///PreferredGameTypeID=1
        ///PreferredScenarioIndex=0
        ///Locale=0
        ///StoreNick=yes
        ///PhoneIndex=-1
        ///WOLLimitResolution=no
        ///LastNickSlot=-1
        ///Color=2
        ///ColorEx=-1
        ///Side=Americans
        ///SideEx=-1
        ///GameMode=1
        ///
        ///[Multiplayer]
        ///GameMode=1
        ///
        ///[Options]
        ///GameSpeed=1
        ///Difficulty=0
        ///ScrollMethod=0
        ///ScrollRate=3
        ///AutoScroll=yes
        ///DetailLevel=2
        ///SidebarCameoText=yes
        ///UnitActionLines=yes
        ///ShowHidden=yes
        ///ToolTips=yes
        ///
        ///[Video]
        ///ScreenWidth=800
        ///ScreenHeight=600
        ///StretchMovies=no
        ///
        ///[Audio]
        ///SoundVolume=0.700000
        ///VoiceVol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ra2ini {
            get {
                return ResourceManager.GetString("ra2ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MultiPlayer]
        ///PreferredGameTypeID=1
        ///PreferredScenarioIndex=0
        ///Locale=0
        ///StoreNick=yes
        ///PhoneIndex=-1
        ///WOLLimitResolution=no
        ///LastNickSlot=-1
        ///Color=2
        ///ColorEx=-1
        ///Side=Americans
        ///SideEx=-1
        ///GameMode=1
        ///
        ///[Multiplayer]
        ///GameMode=1
        ///
        ///[Options]
        ///GameSpeed=1
        ///Difficulty=0
        ///ScrollMethod=0
        ///ScrollRate=3
        ///AutoScroll=yes
        ///DetailLevel=2
        ///SidebarCameoText=yes
        ///UnitActionLines=yes
        ///ShowHidden=yes
        ///ToolTips=yes
        ///
        ///[Video]
        ///ScreenWidth=800
        ///ScreenHeight=600
        ///StretchMovies=no
        ///
        ///[Audio]
        ///SoundVolume=0.700000
        ///VoiceVol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ra2mdini {
            get {
                return ResourceManager.GetString("ra2mdini", resourceCulture);
            }
        }
    }
}
