//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RA2_YR_Config.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RA2_YR_Config.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ddraw]
        ///RealDDrawPath=AUTO
        ///BltMirror=0
        ///BltNoTearing=0
        ///ColorFix=0
        ///DisableHighDpiScaling=0
        ///FakeVsync=0
        ///FakeVsyncInterval=0
        ///ForceBltNoTearing=0
        ///ForceDirectDrawEmulation=0
        ///NoVideoMemory=0
        ///SingleProcAffinity=0
        ///ShowFPS=0
        ///.
        /// </summary>
        internal static string aqrit {
            get {
                return ResourceManager.GetString("aqrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddwrapper {
            get {
                object obj = ResourceManager.GetObject("ddwrapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MultiPlayer]
        ///UnitCount=10
        ///TechLevel=7
        ///StartingCredits=7000
        ///AIPlayers=0
        ///Crates=No
        ///Worms=0
        ///PlayerName=NONAME
        ///PlayerSide=0
        ///PlayerColor=0
        ///PlayerHandicap=0
        ///IPAddress=
        ///ModemPhone=
        ///SerialComPort=1
        ///[Options]
        ///FirstTimePlay=Yes
        ///ScrollRate=20
        ///GameSpeed=75
        ///GameBitsPerPixel=16
        ///SFXVolume=100
        ///MusicVolume=100
        ///MoviesEnabled=Yes
        ///SoundsEnabled=Yes
        ///VideoBackBuffer=Yes
        ///ForceNoCD=Yes
        ///GameWidth=640
        ///GameHeight=400
        ///SlowSideBarScrolling=No
        ///[WOL]
        ///AllowFindUser=Yes
        ///AllowPageUser=Yes
        ///LanguageFilter=No
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dune2000 {
            get {
                return ResourceManager.GetString("dune2000", resourceCulture);
            }
        }
    }
}
